SLASH_REPORTEDTWO1 = "/r2"

REPORTED2_PREFS_SHOW_PANEL = "REPORTED2_SHOW_PANEL"
REPORTED2_PREFS_MUTE_SOUNDS = "REPORTED2_MUTE_SOUNDS"

REPORTED2_DEFAULT_PREFS = {
  [REPORTED2_PREFS_SHOW_PANEL] = true,
  [REPORTED2_PREFS_MUTE_SOUNDS] = false
}
