Events = {}

CHAT_MSG_CHANNEL = "CHAT_MSG_CHANNEL"
CHAT_MSG_GUILD = "CHAT_MSG_GUILD"
CHAT_MSG_OFFICER = "CHAT_MSG_OFFICER"
CHAT_MSG_PARTY = "CHAT_MSG_PARTY"
CHAT_MSG_PARTY_LEADER = "CHAT_MSG_PARTY_LEADER"
CHAT_MSG_RAID = "CHAT_MSG_RAID"
CHAT_MSG_RAID_LEADER = "CHAT_MSG_RAID_LEADER"
CHAT_MSG_SAY = "CHAT_MSG_SAY"
CHAT_MSG_WHISPER = "CHAT_MSG_WHISPER"
CHAT_MSG_YELL = "CHAT_MSG_YELL"

Events.Raw = {
  CHAT_MSG_CHANNEL,
  CHAT_MSG_GUILD,
  CHAT_MSG_OFFICER,
  CHAT_MSG_PARTY_LEADER,
  CHAT_MSG_PARTY,
  CHAT_MSG_RAID_LEADER,
  CHAT_MSG_RAID,
  CHAT_MSG_SAY,
  CHAT_MSG_WHISPER,
  CHAT_MSG_YELL
}

Events.Readable = {
  [CHAT_MSG_CHANNEL] = "Channel",
  [CHAT_MSG_GUILD] = "Guild",
  [CHAT_MSG_OFFICER] = "Officer",
  [CHAT_MSG_PARTY_LEADER] = "Party",
  [CHAT_MSG_PARTY] = "Party",
  [CHAT_MSG_RAID_LEADER] = "Raid",
  [CHAT_MSG_RAID] = "Raid",
  [CHAT_MSG_SAY] = "Say",
  [CHAT_MSG_WHISPER] = "Whisper",
  [CHAT_MSG_YELL] = "Yell"
}

Events.Colours = {
  [CHAT_MSG_CHANNEL] = "E8E079",
  [CHAT_MSG_GUILD] = "40FB40",
  [CHAT_MSG_OFFICER] = "40BD40",
  [CHAT_MSG_PARTY_LEADER] = "76C5FF",
  [CHAT_MSG_PARTY] = "AAA7FF",
  [CHAT_MSG_RAID_LEADER] = "FF4709",
  [CHAT_MSG_RAID] = "FF7D00",
  [CHAT_MSG_SAY] = "FFFFFF",
  [CHAT_MSG_WHISPER] = "FF7EFF",
  [CHAT_MSG_YELL] = "FF3F40"
}
