name: "Tagged Release"

on:
  push:
    tags:
      - "**"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: ${GITHUB_REF#refs/*/}

    steps:
      - name: Checkout code and generate TOC files
        uses: actions/checkout@v3

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: mkdir -p Reported2
      - run: touch Reported2.toc.tmp
      - run: cat Reported2.toc > Reported2.toc.tmp
      - run: sed -i "s/@project-version@/${{ env.RELEASE_VERSION }}/g" Reported2.toc.tmp
      - run: cp *.lua ./Reported2/
      - run: cp -r Fonts/ ./Reported2/
      - run: cp -r Sounds/ ./Reported2/
      - run: cp -r Textures/ ./Reported2/
      - run: cp Reported2.toc.tmp ./Reported2/Reported2.toc

      - name: Build zip
        uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a Reported2-${{ env.RELEASE_VERSION }}.zip ./Reported2/

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Reported2-${{ env.RELEASE_VERSION }}.zip
