name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p Reported2

      - run: cp *.lua *.toc *.mp3 *.tga ./Reported2/

      - run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Set interface version for Retail
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.toc"]'
        env:
          INTERFACE_VERSION: 80300

      - name: Build Retail zip
        uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a Reported2-${{ env.RELEASE_VERSION }}.zip ./Reported2/

      - name: Set interface version for Retail
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.toc"]'
        env:
          INTERFACE_VERSION: 11305

      - name: Build Classic zip
        uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a Reported2-${{ env.RELEASE_VERSION }}-classic.zip ./Reported2/

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Reported2-${{ env.RELEASE_VERSION }}.zip
            Reported2-${{ env.RELEASE_VERSION }}-classic.zip
