name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p Reported2

    - run: cp *.lua *.toc ./Reported2/
    
    - name: Build Retail zip
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a Reported2.zip ./Reported2/

    - name: Publish Release (Retail)
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: Reported2-${{ github.event.release.tag_name }}.zip
